// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PantryItem struct {
	ID           pgtype.UUID
	Name         string
	Quantity     pgtype.Numeric
	Unit         string
	Price        pgtype.Numeric
	ExpirationMs pgtype.Int8
	Category     string
	Userid       pgtype.UUID
}

type Recipe struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	Steps       []string
	Ingredients []string
	Creatorid   pgtype.UUID
}

type User struct {
	ID    pgtype.UUID
	Email string
	Name  string
}
