// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_item_entries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getUserItemEntryIdsForUser = `-- name: GetUserItemEntryIdsForUser :many
SELECT
  id
FROM
  UserItemEntries
WHERE
  user_id = $1
`

func (q *Queries) GetUserItemEntryIdsForUser(ctx context.Context, userID *uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getUserItemEntryIdsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
