// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_item_entries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getUserItemEntryIngredientIdsForUser = `-- name: GetUserItemEntryIngredientIdsForUser :many
SELECT
  ingredient_id
FROM
  UserItemEntries
WHERE
  user_id = $1
`

func (q *Queries) GetUserItemEntryIngredientIdsForUser(ctx context.Context, userID *uuid.UUID) ([]*uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getUserItemEntryIngredientIdsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*uuid.UUID
	for rows.Next() {
		var ingredient_id *uuid.UUID
		if err := rows.Scan(&ingredient_id); err != nil {
			return nil, err
		}
		items = append(items, ingredient_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
